version: 0
metadata:
  name: "test"
  description: "IamamwhoamI"
  owner: "mphillips@mozilla.com"
  source: "{{ headRepoUrl }}"
tasks:
  - provisionerId: aws-provisioner-v1
    workerType: b2g-desktop-opt
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.*
    payload:
      image: "ubuntu:latest"
      command:
        - "/bin/bash"
        - "-c"
        - "echo 'I run on all the things'"
    metadata:
      name: "test"
      description: "IamamwhoamI"
      owner: "mphillips@mozilla.com"
      source: "{{ headRepoUrl }}"
