---
version: 0
tasks:
  - extra:
      github:
        events:
          - push
          - pull_request.*
    payload:
      image: "ubuntu:latest"
      env: "{{ $githubEnvs }}"
      command:
        - "/bin/bash"
        - "-c"
        - "echo 'I run on all the things'"
    metadata:
	name: "test",
	description: "IamamwhoamI",
	owner: "mphillips@mozilla.com",
	source: "{{ organization }}"
