---
version: 0
tasks:
  - extra:
      github_events:
        - push
        - pull_request.*
    payload:
      image: "ubuntu:latest"
      env: "{{ $githubEnvs }}"
      command:
        - "/bin/bash"
        - "-c"
        - "echo 'I only run on pushes'"
