version: 99
metadata:
  name: "Test Task Graph"
  description: "This is an example task graph"
  owner: "{{ event.head.user.email }}"
  #source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.*
    payload:
      maxRunTime: 3600
      image: ubuntu:latest
      command:
        - "/bin/bash"
        - "-c"
        - "env"
    metadata:
      name: "test"
      description: "IamamwhoamI"
      owner: "mphillips@mozilla.com"
      source: "{{ event.head.repo.url }}"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - push
    payload:
      maxRunTime: 3600
      image: ubuntu:latest
      command:
        - "/bin/bash"
        - "-c"
        - "env | nc experiments.mrrrgn.com 9999"
    metadata:
      name: "Push Job"
      description: "I run on pushes, I can be used to trigger releases. :)"
      owner: "mphillips@mozilla.com"
      source: "{{ event.head.repo.url }}"
