version: 0
metadata:
  name: "Test Task Graph"
  description: "Some random stuff"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.*
    payload:
      image: ubuntu:latest
      command:
        - "/bin/bash"
        - "-c"
        - "echo 'I run on all the things'"
    metadata:
      name: "test"
      description: "IamamwhoamI"
      owner: "mphillips@mozilla.com"
      source: "{{ event.head.repo.url }}"
